language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=940fcf067bbe7a558fda21525e8a96d6a67c844096b0e6c63e4e27877d142324
